"""update

Revision ID: e16f81705cd9
Revises: bf23dc678217
Create Date: 2025-05-16 19:39:47.856463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16f81705cd9'
down_revision: Union[str, None] = 'bf23dc678217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('active', 'inactive', 'suspended'), nullable=False))
    op.add_column('users', sa.Column('suspended_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'suspended_until')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
